AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TenderTool Backend — Scrapers, Normalizer, and Tender API
  Deployed via GitHub Actions with AWS SAM (Node 20 runtime)

Parameters:
  StageEnv:
    Type: String
    Default: dev
    AllowedValues: [dev]

  DataBucketName:
    Type: String
    Default: tender-scraper-bucket

  IngestQueueArn:
    Type: String
    Default: arn:aws:sqs:af-south-1:483647879571:tt-etl-ingest-queue

  VpcSubnetIds:
    Type: CommaDelimitedList
    Default: subnet-09214163b67aa4a0e,subnet-000aff0b975da8813,subnet-00a5a8eccd1cc5857

  VpcSecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-004944b29da471d8b

  RdsHost:
    Type: String
    Default: tt-postgres.c16a2miq4p2h.af-south-1.rds.amazonaws.com

  RdsPort:
    Type: String
    Default: "5432"

  TenderTopicArn:
    Type: String
    Default: arn:aws:sns:af-south-1:483647879571:tender-topic

  DbPasswordParamName:
    Type: String
    Default: /tendertool/dev/db/password

  DbUser:
    Type: String
    Default: tender_app

  DbName:
    Type: String
    Default: tenders

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures: [x86_64]     
    Timeout: 90
    MemorySize: 1024
    Environment:
      Variables:
        STAGE: !Ref StageEnv
        RAW_DATA_BUCKET: !Ref DataBucketName
        INGEST_QUEUE_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/tt-etl-ingest-queue
        RDS_HOST: !Ref RdsHost
        RDS_PORT: !Ref RdsPort

Resources:

  #########################################
  # HTTP API  #
  #########################################
  TenderHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageEnv
      CorsConfiguration:
        AllowOrigins: 
          - '*'
        AllowHeaders: 
          - content-type
          - authorization
          - x-requested-with
        AllowMethods: 
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: 300
        AllowCredentials: false
      Tags:
        AutoDeploy: "true"

  ####################
  # ESKOM SCRAPER    #
  ####################
  EskomScraperFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-eskom-scraper-${StageEnv}
      CodeUri: lambdas/eskom-scraper
      Handler: index.handler
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - S3CrudPolicy: { BucketName: !Ref DataBucketName }
        - SQSSendMessagePolicy: { QueueName: tt-etl-ingest-queue }
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 4 * * ? *)
            Name: !Sub tt-eskom-schedule-${StageEnv}

  ####################
  # TRANSNET SCRAPER #
  ####################
  TransnetScraperFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-transnet-scraper-${StageEnv}
      CodeUri: lambdas/transnet-scraper
      Handler: index.handler
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - S3CrudPolicy: { BucketName: !Ref DataBucketName }
        - SQSSendMessagePolicy: { QueueName: tt-etl-ingest-queue }
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(10 4 * * ? *)
            Name: !Sub tt-transnet-schedule-${StageEnv}

  ##################
  # SANRAL SCRAPER #
  ##################
  SanralScraperFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-sanral-scraper-${StageEnv}
      CodeUri: lambdas/sanral-scraper
      Handler: index.handler
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - S3CrudPolicy: { BucketName: !Ref DataBucketName }
        - SQSSendMessagePolicy: { QueueName: tt-etl-ingest-queue }
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(20 4 * * ? *)
            Name: !Sub tt-sanral-schedule-${StageEnv}
    
  ###################
  # ETENDERS FETCHER #
  ###################
  EtendersFetcherFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-etenders-fetcher-${StageEnv}
      CodeUri: lambdas/etenders-fetcher
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Environment:
        Variables:
          BUCKET: !Ref DataBucketName
          PREFIX: "etenders/"
          PAGE_SIZE: "100"
          MAX_PAGES: "50"
          THROTTLE_MS: "3000"
          USE_CONCURRENT: "false"
          INGEST_QUEUE_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/tt-etl-ingest-queue
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - S3CrudPolicy: { BucketName: !Ref DataBucketName }
        - SQSSendMessagePolicy: { QueueName: tt-etl-ingest-queue }
        - Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/tt-etenders-fetcher-${StageEnv}
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 4 * * ? *)
            Name: !Sub tt-etenders-schedule-${StageEnv}

  ###############
  # NORMALIZER  #
  ###############
  NormalizerFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-normalizer-${StageEnv}
      CodeUri: lambdas/normalizer
      Handler: index.handler
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - SQSPollerPolicy: { QueueName: tt-etl-ingest-queue }
        - S3ReadPolicy: { BucketName: !Ref DataBucketName }
      Events:
        IngestQueueEvent:
          Type: SQS
          Properties:
            Queue: !Ref IngestQueueArn
            BatchSize: 5
            Enabled: true

  ##########################
  # TENDER API (via HttpApi)
  ##########################
  TenderApiHandlerFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-tender-api-handler-${StageEnv}
      CodeUri: lambdas/tender-api-handler
      Handler: index.handler
      Timeout: 30
      MemorySize: 1024
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sns:Subscribe
                - sns:Unsubscribe
                - sns:ListSubscriptionsByTopic
              Resource: !Ref TenderTopicArn
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/tendertool/*
      Environment:
        Variables:
          DB_HOST: !Ref RdsHost
          DB_PORT: !Ref RdsPort
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD_PARAM: !Ref DbPasswordParamName
          TENDER_TOPIC_ARN: !Ref TenderTopicArn
      Events:
        Proxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref TenderHttpApi
            Path: /{proxy+}
            Method: ANY

  TenderSummariserFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tt-tender-summariser-${StageEnv}
      CodeUri: lambdas/tender-summariser
      Handler: index.handler
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_PARAM: /tendertool/dev/openai/api-key
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: ssm:GetParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/tendertool/*
      Events:
        SummariseRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref TenderHttpApi
            Path: /summarise
            Method: POST


